---
# handlers file for ansible-role-dada2

- name: Remove biol tmp dir
  file:
    state: absent
    path: "/tmp/biol/"

- name: Remove DADA2 install template
  file:
    state: absent
    path: "{{ base_path }}/.biolighthouse/software/install_dada2.R"

- name: Remove environment activation in .bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    regexp: "^conda activate bl_*"
    state: absent
